// <auto-generated />
using Labb_3_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb_3_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423082232_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb_3_API.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Rock climbing and bouldering",
                            Title = "Climbing"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Video games and esports",
                            Title = "Gaming"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Long distance running",
                            Title = "Running"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Making food and recipes",
                            Title = "Cooking"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Playing instruments and listening",
                            Title = "Music"
                        });
                });

            modelBuilder.Entity("Labb_3_API.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("UserId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            Url = "https://climbing.com",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 2,
                            Url = "https://twitch.tv",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 2,
                            Url = "https://gaming.com",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 4,
                            Url = "https://recipes.com",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            InterestId = 3,
                            Url = "https://runfast.com",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            InterestId = 1,
                            Url = "https://climbworld.com",
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            InterestId = 5,
                            Url = "https://spotify.com",
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            InterestId = 4,
                            Url = "https://foodblog.com",
                            UserId = 5
                        },
                        new
                        {
                            Id = 9,
                            InterestId = 3,
                            Url = "https://marathon.com",
                            UserId = 6
                        },
                        new
                        {
                            Id = 10,
                            InterestId = 2,
                            Url = "https://esports.com",
                            UserId = 7
                        });
                });

            modelBuilder.Entity("Labb_3_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "erik@mail.com",
                            FirstName = "Erik",
                            LastName = "Larsson",
                            PhoneNumber = "0701111111"
                        },
                        new
                        {
                            Id = 2,
                            Email = "anna@mail.com",
                            FirstName = "Anna",
                            LastName = "Svensson",
                            PhoneNumber = "0702222222"
                        },
                        new
                        {
                            Id = 3,
                            Email = "johan@mail.com",
                            FirstName = "Johan",
                            LastName = "Karlsson",
                            PhoneNumber = "0703333333"
                        },
                        new
                        {
                            Id = 4,
                            Email = "lisa@mail.com",
                            FirstName = "Lisa",
                            LastName = "Andersson",
                            PhoneNumber = "0704444444"
                        },
                        new
                        {
                            Id = 5,
                            Email = "oskar@mail.com",
                            FirstName = "Oskar",
                            LastName = "Nilsson",
                            PhoneNumber = "0705555555"
                        },
                        new
                        {
                            Id = 6,
                            Email = "emma@mail.com",
                            FirstName = "Emma",
                            LastName = "Johansson",
                            PhoneNumber = "0706666666"
                        },
                        new
                        {
                            Id = 7,
                            Email = "lucas@mail.com",
                            FirstName = "Lucas",
                            LastName = "Eriksson",
                            PhoneNumber = "0707777777"
                        },
                        new
                        {
                            Id = 8,
                            Email = "maja@mail.com",
                            FirstName = "Maja",
                            LastName = "Persson",
                            PhoneNumber = "0708888888"
                        },
                        new
                        {
                            Id = 9,
                            Email = "albin@mail.com",
                            FirstName = "Albin",
                            LastName = "Gustafsson",
                            PhoneNumber = "0709999999"
                        },
                        new
                        {
                            Id = 10,
                            Email = "sara@mail.com",
                            FirstName = "Sara",
                            LastName = "Berg",
                            PhoneNumber = "0701010101"
                        });
                });

            modelBuilder.Entity("Labb_3_API.Models.UserInterest", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UserInterests");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            InterestId = 1,
                            Id = 0
                        },
                        new
                        {
                            UserId = 1,
                            InterestId = 2,
                            Id = 0
                        },
                        new
                        {
                            UserId = 2,
                            InterestId = 2,
                            Id = 0
                        },
                        new
                        {
                            UserId = 2,
                            InterestId = 4,
                            Id = 0
                        },
                        new
                        {
                            UserId = 3,
                            InterestId = 3,
                            Id = 0
                        },
                        new
                        {
                            UserId = 3,
                            InterestId = 1,
                            Id = 0
                        },
                        new
                        {
                            UserId = 4,
                            InterestId = 5,
                            Id = 0
                        },
                        new
                        {
                            UserId = 5,
                            InterestId = 4,
                            Id = 0
                        },
                        new
                        {
                            UserId = 6,
                            InterestId = 3,
                            Id = 0
                        },
                        new
                        {
                            UserId = 7,
                            InterestId = 2,
                            Id = 0
                        },
                        new
                        {
                            UserId = 8,
                            InterestId = 1,
                            Id = 0
                        },
                        new
                        {
                            UserId = 9,
                            InterestId = 5,
                            Id = 0
                        },
                        new
                        {
                            UserId = 10,
                            InterestId = 2,
                            Id = 0
                        });
                });

            modelBuilder.Entity("Labb_3_API.Models.Link", b =>
                {
                    b.HasOne("Labb_3_API.Models.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb_3_API.Models.User", "User")
                        .WithMany("Links")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Labb_3_API.Models.UserInterest", b =>
                {
                    b.HasOne("Labb_3_API.Models.Interest", "Interest")
                        .WithMany("UserInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb_3_API.Models.User", "User")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Labb_3_API.Models.Interest", b =>
                {
                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("Labb_3_API.Models.User", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("UserInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
